import mongoose from "mongoose";

/**
 * Source Schema - Flat structure for individual sources
 * Each source is stored as a separate document reference or embedded
 */
const sourceSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true,
        trim: true,
    },
    url: {
        type: String,
        required: true,
        trim: true,
    },
    category: {
        type: String,
        enum: ["clinical", "protein", "compound", "pathway", "trials", "general"],
        default: "general",
    },
    database: {
        type: String,
        default: "unknown",
    },
    contentLength: {
        type: Number,
        default: 0,
    },
    status: {
        type: String,
        enum: ["crawl", "snippet", "search", "rawContent", "failed"],
        default: "search",
    },
});

/**
 * Research Result Schema - Main schema for storing complete drug discovery results
 * Designed with flat structure for optimal query performance
 */
const researchResultSchema = new mongoose.Schema(
    {
        // Reference to the user who created this research
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
            index: true,
        },

        // Original input query/symptoms
        symptoms: {
            type: String,
            required: true,
            trim: true,
        },

        // Extracted/processed symptoms
        extractedSymptoms: {
            type: String,
            trim: true,
        },

        // Research mode
        mode: {
            type: String,
            default: "comprehensive-research",
        },

        // Main content/dossier generated by AI
        content: {
            type: String,
            required: true,
        },

        // Sources - stored as embedded documents (limited number, typically < 20)
        sources: [sourceSchema],

        // Research Plan - Flat structure instead of nested objects
        researchPlanStrategy: {
            type: String,
            default: "",
        },

        researchPlanHypotheses: {
            type: [String],
            default: [],
        },

        researchPlanTargetDatabases: {
            type: [String],
            default: [],
        },

        // Metadata - Flat structure for performance
        metadataTotalDuration: {
            type: String,
            default: "",
        },

        metadataQueriesExecuted: {
            type: Number,
            default: 0,
        },

        metadataSourcesFound: {
            type: Number,
            default: 0,
        },

        metadataSourcesCrawled: {
            type: Number,
            default: 0,
        },

        metadataSourcesUsed: {
            type: Number,
            default: 0,
        },

        metadataSourceBreakdownClinical: {
            type: Number,
            default: 0,
        },

        metadataSourceBreakdownProtein: {
            type: Number,
            default: 0,
        },

        metadataSourceBreakdownCompound: {
            type: Number,
            default: 0,
        },

        metadataSourceBreakdownPathway: {
            type: Number,
            default: 0,
        },

        metadataSourceBreakdownTrials: {
            type: Number,
            default: 0,
        },

        metadataSourceBreakdownGeneral: {
            type: Number,
            default: 0,
        },

        metadataModelUsed: {
            type: String,
            default: "",
        },

        metadataTimestamp: {
            type: Date,
            default: Date.now,
        },

        metadataErrors: {
            type: [String],
            default: [],
        },

        // Content statistics
        contentLength: {
            type: Number,
            default: 0,
        },

        // Search statistics for analytics
        searchStats: {
            queriesExecuted: { type: Number, default: 0 },
            sourcesFound: { type: Number, default: 0 },
            sourcesCrawled: { type: Number, default: 0 },
            sourcesUsed: { type: Number, default: 0 },
        },

        // Tags for organization
        tags: {
            type: [String],
            default: [],
        },

        // User notes
        notes: {
            type: String,
            default: "",
        },

        // Soft delete flag
        isDeleted: {
            type: Boolean,
            default: false,
        },

        // Starred/Favorite flag
        isStarred: {
            type: Boolean,
            default: false,
        },
    },
    {
        timestamps: true, // Adds createdAt and updatedAt
    }
);

// Indexes for common queries
researchResultSchema.index({ userId: 1, createdAt: -1 }); // For fetching user's research history
researchResultSchema.index({ userId: 1, isStarred: 1 }); // For fetching starred items
researchResultSchema.index({ symptoms: "text", content: "text" }); // For text search
researchResultSchema.index({ tags: 1 }); // For tag-based filtering
researchResultSchema.index({ isDeleted: 1 }); // For soft delete filtering

// Pre-save middleware to calculate content length
researchResultSchema.pre("save", function () {
    if (this.content) {
        this.contentLength = this.content.length;
    }
});

// Instance method to get summary
researchResultSchema.methods.getSummary = function () {
    return {
        id: this._id,
        symptoms: this.symptoms,
        extractedSymptoms: this.extractedSymptoms,
        mode: this.mode,
        sourceCount: this.sources?.length || 0,
        contentPreview: this.content?.substring(0, 200) + "...",
        metadataTotalDuration: this.metadataTotalDuration,
        metadataSourcesUsed: this.metadataSourcesUsed,
        metadataModelUsed: this.metadataModelUsed,
        createdAt: this.createdAt,
        isStarred: this.isStarred,
        tags: this.tags,
    };
};

// Static method to get user's research history
researchResultSchema.statics.getUserHistory = async function (
    userId,
    options = {}
) {
    const { limit = 20, skip = 0, includeDeleted = false } = options;

    const query = { userId };
    if (!includeDeleted) {
        query.isDeleted = false;
    }

    return this.find(query)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .select(
            "symptoms extractedSymptoms mode sources metadataTotalDuration metadataSourcesUsed metadataModelUsed createdAt isStarred tags content"
        )
        .lean();
};

// Static method to search user's research
researchResultSchema.statics.searchUserResearch = async function (
    userId,
    searchTerm,
    options = {}
) {
    const { limit = 20, skip = 0 } = options;

    return this.find({
        userId,
        isDeleted: false,
        $text: { $search: searchTerm },
    })
        .sort({ score: { $meta: "textScore" } })
        .skip(skip)
        .limit(limit)
        .select(
            "symptoms extractedSymptoms mode sources metadataTotalDuration metadataSourcesUsed createdAt isStarred tags content"
        )
        .lean();
};

const ResearchResult = mongoose.model("ResearchResult", researchResultSchema);

export default ResearchResult;
